[general]
base_url = "http://sequencer.heurist.xyz"
num_cuda_devices = 1
miner_id_0 = "0x9b36900555d304a5BDdC0bD361edBD1a653c8b79"
log_filename = "sd-miner.log"

s3_bucket = 'heurist-images'
model_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/models.json"
vae_config_url = "https://raw.githubusercontent.com/heurist-network/heurist-models/main/vae.json"
base_dir = "~/.cache/heurist"
min_deadline = 1

max_iterations = 50
max_width = 1024
max_height = 1024
